[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/sharp/**/*"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_SHARP_PATH = "/node_modules/sharp"